apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-expressjs-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd-expressjs-demo
  template:
    metadata:
      labels:
        app: argocd-expressjs-demo
    spec:
      containers:
        - image: streitbegasoftch/argocd-expressjs-demo:latest
          name: argocd-expressjs-demo
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
